'use strict'

const express = require("express")
const { asyncHandler } = require("../../auth/checkAuth")
const router = express.Router()
const userController = require("../../controllers/user.controller")
const  orderController  = require("../../controllers/order.controller")
const { authenticate } = require("../../middlewares/authenticate")
const upload = require("../../config/cloudinary.config")
const cartController = require("../../controllers/cart.controller")

router.get("/:user_id", authenticate, asyncHandler(userController.getInfoUser))
router.get("/:user_id", authenticate, asyncHandler(userController.getInfoUser))
router.post("/:user_id/tours", authenticate, asyncHandler(userController.proposeTour))
router.get("/:user_id/groups", authenticate, asyncHandler(userController.getAllGroupsByUserId))
router.get("/:user_id/cart", authenticate, asyncHandler(cartController.getCartByUser))
router.get("/:user_id/pendingtour", authenticate, asyncHandler(userController.getPendingTour))
router.get("/:user_id/rejectedtour", authenticate, asyncHandler(userController.getRejectTour))
router.get("/:user_id/successtour", authenticate, asyncHandler(userController.getSuccessTour))
router.get("/:user_id/completed_order", asyncHandler(orderController.getCompleteOrderByUser))
router.get("/:user_id/failed_order", asyncHandler(orderController.getFailedOrderByUser))
router.post("/change-password", authenticate, asyncHandler(userController.changePassword))
router.get("/:user_id/wishlist", authenticate, asyncHandler(userController.getWishlistByCustomer))
router.post("/wishlist", authenticate, asyncHandler(userController.addTourToWishlist))
router.delete("/wishlist", authenticate, asyncHandler(userController.removeTourFromWishlist))
router.put("/:user_id", authenticate, asyncHandler(userController.updateInfoUser))
router.post("/:user_id/upload", authenticate, upload.single("avatar"), asyncHandler(userController.uploadAvatar))
router.post("/forgot-password", asyncHandler(userController.forgotPassword))
router.post("/reset-password",  asyncHandler(userController.resetPassword))

module.exports = router